openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is documentation of students app
servers:
  - url: http://localhost:3000
  - url: https://contactsapp-go5k.onrender.com
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
paths:
  /contacts:
    get:
      $ref: ./paths/contacts/get.yaml
    post:
      $ref: ./paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ./paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ./paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ./paths/contacts/{contactId}/delete.yaml
  /auth/login:
    post:
      $ref: ./paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ./paths/auth/logout/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
